version: '3.7'
services:
  web:
    image:  gftd-exchange-web:latest
    container_name: gftd-exchange-web
    build:
      context: .
      cache_from:
        - web-gftd-exchange:latest
#   entrypoint: /var/www/entrypoint.sh
    depends_on:
      - mysql
      - redis
    restart: always
    env_file:
      - ../.env
    working_dir: /var/www
    volumes:
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./nginx_app.conf:/etc/nginx/sites-enabled/app.conf
      - ../:/var/www
    ports:
      - "80:80"
#    command: bash -c "foreman start -f Procfile"
    tty: true
    stdin_open: true
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    container_name: gftd-exchange-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'gftd-exchange-db'
      MYSQL_USER: 'gftd-exchange-us'
      MYSQL_PASSWORD: 'n9pGwYA24CUFjpCxGy2u949'
      MYSQL_ROOT_PASSWORD: 'Ux4gAR5TACketX9DzkEaJGG'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    container_name: gftd-exchange-redis
volumes:
  mysql-volume:
