name: Rokes Tests

on:
  pull_request:
      types: [opened, edited]
      branch: master
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('dockerize/.env-dev', '.env');"
      - name: Build image
        run: docker-compose build web
      - name: Run docker-compose
        run: |
             docker-compose up -d
             docker exec gftd-exchange-web chown -R www-data bootstrap/cache/ 
             docker exec gftd-exchange-web chown -R www-data storage/
             docker exec gftd-exchange-web composer install
             docker exec gftd-exchange-web php artisan key:generate
             docker exec gftd-exchange-web php artisan config:clear
             docker exec gftd-exchange-web php artisan migrate --force
             docker exec gftd-exchange-web php artisan db:seed --force
             docker exec gftd-exchange-web php artisan storage:link
      - name: Run tests
        run: docker exec gftd-exchange-web vendor/bin/phpunit
