name: Rokes Tests

on:
  pull_request:
      types: opened
      branch: master
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('dockerize/.env-dev', '.env');"
      - name: Build image
        run: docker-compose -f dockerize/docker-compose.yml build web
      - name: Run docker-compose
        run: |
             docker-compose up -d
             docker ps
             docker-compose exec -T web chown -R www-data bootstrap/cache/ 
             docker-compose exec -T web chown -R www-data storage/
             docker-compose exec -T web composer install
             docker-compose exec -T web php artisan key:generate
             docker-compose exec -T web php artisan config:clear
             docker-compose exec -T web php artisan migrate --force
             docker-compose exec -T web php artisan db:seed --force
             docker-compose exec -T web php artisan storage:link
             docker-compose restart
      - name: Run tests
        run: docker-compose exec -T web vendor/bin/phpunit
