name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('dockerize/.env-dev', '.env');"
    - name: Docker build
      run: docker-compose build web
    - name: Deploy system
      run: docker-compose up -d 
           docker-compose exec web chown -R www-data bootstrap/cache/ 
           docker-compose exec web chown -R www-data storage/ 
           docker-compose exec web composer install 
           docker-compose exec web php artisan key:generate 
           docker-compose exec web php artisan config:clear 
           docker-compose exec web php artisan migrate --force 
           docker-compose exec web php artisan db:seed --force 
           docker-compose exec web php artisan storage:link 
           docker-compose restart  
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan web vendor/bin/phpunit
